import { StyleSheet, Dimensions, Platform } from 'react-native';

const { width: screenWidth } = Dimensions.get('window');
export const drawerWidth = Platform.OS === 'web' ? 366 : screenWidth;

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#000000',
  },
  fluidBackground: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 0,
    opacity: 0.95,
  },
  litBorderOverlay: {
    ...StyleSheet.absoluteFill,
    borderWidth: 1.2,
    borderColor: '#3b82f6',
    borderRadius: Platform.OS === 'web' ? 32 : 0,
    zIndex: 999,
    ...Platform.select({
      web: {
        boxShadow: '0px 0px 12px rgba(59, 130, 246, 0.8)',
      },
      default: {
        shadowColor: '#3b82f6',
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.8,
        shadowRadius: 12,
        elevation: 8,
      },
    }),
  },
  mainWrapper: {
    flex: 1,
    paddingTop: Platform.OS === 'web' ? 40 : 0,
    zIndex: 1,
  },
  navBar: {
    flexDirection: 'row',
    height: 50,
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#171717',
    zIndex: 10,
  },
  navButton: {
    width: 36,
    height: 36,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  navTitle: {
    fontSize: 16,
    fontWeight: '400',
    color: '#ffffff',
    flex: 1,
    textAlign: 'center',
    marginHorizontal: 12,
    letterSpacing: -0.4,
  },
  welcomeContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
    gap: 20,
  },
  welcomeText: {
    fontSize: 30,
    fontWeight: '300',
    color: '#ffffff',
    textAlign: 'center',
    letterSpacing: -0.6,
    lineHeight: 38,
  },
  chatListContent: {
    padding: 12,
    gap: 12,
    paddingBottom: 20,
  },
  userBubbleWrapper: {
    alignSelf: 'flex-end',
    maxWidth: '92%',
    marginBottom: 4,
  },
  userBubble: {
    backgroundColor: '#262626',
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  userMessageText: {
    color: '#ffffff',
    fontSize: 14.5,
    lineHeight: 20,
    letterSpacing: -0.2,
    fontWeight: '400',
  },
  assistantBubbleWrapper: {
    flexDirection: 'row',
    gap: 10,
    alignSelf: 'flex-start',
    maxWidth: '96%',
    marginBottom: 4,
  },
  assistantAvatar: {
    width: 28,
    height: 28,
    borderRadius: 8,
    backgroundColor: '#0c1222',
    justifyContent: 'center',
    alignItems: 'center',
    borderColor: '#1e293b',
    borderWidth: 1,
  },
  avatarText: {
    color: '#2563eb',
    fontWeight: 'bold',
    fontSize: 13,
  },
  assistantBubble: {
    flexShrink: 1,
    flexGrow: 1,
    backgroundColor: 'rgba(8, 8, 8, 0.6)',
    borderColor: 'rgba(255, 255, 255, 0.05)',
    borderWidth: 1,
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 10,
    ...Platform.select({
      web: {
        backdropFilter: 'blur(12px)',
        boxShadow: '0 4px 16px rgba(0, 0, 0, 0.2)',
      },
      default: {},
    }),
  },
  typingIndicatorContainer: {
    marginTop: 6,
    alignItems: 'flex-start',
  },
  thinkingBubble: {
    minWidth: 180,
  },
  thinkingHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 4,
  },
  thinkingSpinner: {
    marginRight: 6,
  },
  thinkingTitle: {
    color: '#60a5fa',
    fontSize: 12,
    fontWeight: '600',
  },
  thinkingStatusText: {
    color: '#94a3b8',
    fontSize: 11,
    fontStyle: 'italic',
    paddingLeft: 20,
  },
  streamingStatusRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 4,
  },
  streamingStatusText: {
    color: '#94a3b8',
    fontSize: 11,
    fontStyle: 'italic',
  },
  laptopLogWrapper: {
    flexDirection: 'row',
    alignSelf: 'stretch',
    marginVertical: 4,
    paddingLeft: 38,
  },
  laptopLogBar: {
    width: 2,
    backgroundColor: '#2563eb',
    borderRadius: 1,
    marginRight: 10,
  },
  laptopLogCard: {
    flex: 1,
    backgroundColor: '#171717',
    borderWidth: 1,
    borderColor: '#262626',
    borderRadius: 10,
    padding: 10,
  },
  laptopLogHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 4,
  },
  laptopLogTitle: {
    fontSize: 11,
    fontWeight: '600',
    color: '#2563eb',
  },
  laptopLogText: {
    fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
    fontSize: 11.5,
    color: '#9ca3af',
    lineHeight: 15,
  },
  inputAreaContainer: {
    padding: 12,
    paddingBottom: Platform.OS === 'ios' ? 24 : 16,
  },
  inputPill: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    backgroundColor: '#0c0c0c',
    borderWidth: 1,
    borderColor: '#171717',
    borderRadius: 24,
    paddingHorizontal: 6,
    paddingBottom: 6,
    paddingTop: 6,
    minHeight: 48,
    ...Platform.select({
      web: {
        boxShadow: '0 4px 12px rgba(0, 0, 0, 0.3)',
      },
      default: {},
    }),
  },
  inputAddBtn: {
    padding: 6,
    marginBottom: Platform.OS === 'web' ? 2 : 0,
  },
  inputField: {
    flex: 1,
    color: '#f8fafc',
    fontSize: 14.5,
    paddingHorizontal: 8,
    paddingTop: Platform.OS === 'web' ? 8 : 6,
    paddingBottom: Platform.OS === 'web' ? 8 : 6,
    maxHeight: 150,
    ...Platform.select({
      web: {
        outlineStyle: 'none',
      } as any,
      default: {},
    }),
  },
  inputVoiceBtn: {
    padding: 8,
    marginBottom: Platform.OS === 'web' ? 1 : 0,
  },
  inputSendBtn: {
    padding: 4,
    marginBottom: Platform.OS === 'web' ? 2 : 0,
  },
  sendCircle: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#1e293b',
    justifyContent: 'center',
    alignItems: 'center',
  },
  sendCircleActive: {
    backgroundColor: '#3b82f6',
    ...Platform.select({
      web: {
        boxShadow: '0 0 8px rgba(59, 130, 246, 0.5)',
      },
      default: {},
    }),
  },
  capsulesContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 8,
    paddingHorizontal: 4,
  },
  capsule: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    backgroundColor: '#0c0c0c',
    borderColor: '#171717',
    borderWidth: 1,
  },
  capsuleText: {
    fontSize: 11,
    fontWeight: '600',
    color: '#94a3b8',
  },
  voiceOverlay: {
    ...StyleSheet.absoluteFill,
    backgroundColor: 'rgba(13, 13, 13, 0.95)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 200,
  },
  voiceTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: '#ffffff',
    marginBottom: 20,
  },
  voiceIndicator: {
    marginBottom: 20,
    transform: [{ scale: 1.3 }],
  },
  voiceSubtitle: {
    fontSize: 13,
    color: '#6b7280',
  },
  drawerBackdrop: {
    ...StyleSheet.absoluteFill,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    zIndex: 100,
  },
  sidebarDrawer: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    width: 280,
    backgroundColor: '#080808',
    borderRightWidth: 1,
    borderRightColor: '#171717',
    paddingTop: Platform.OS === 'web' ? 40 : 0,
    zIndex: 101,
  },
  sidebarHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    height: 50,
    paddingHorizontal: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#171717',
    gap: 8,
  },
  sidebarTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: '#ffffff',
    flex: 1,
  },
  newChatBtn: {
    margin: 12,
    marginBottom: 6,
    height: 42,
    borderRadius: 10,
    backgroundColor: '#2563eb',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 8,
  },
  newChatBtnText: {
    color: '#ffffff',
    fontWeight: '500',
    fontSize: 13,
    letterSpacing: -0.2,
  },
  sidebarPlaygroundBtn: {
    marginHorizontal: 12,
    marginBottom: 12,
    height: 40,
    borderRadius: 10,
    backgroundColor: '#0f0f0f',
    borderWidth: 1,
    borderColor: '#171717',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 8,
  },
  sidebarPlaygroundText: {
    color: '#ffffff',
    fontWeight: '500',
    fontSize: 13,
    letterSpacing: -0.2,
  },
  historyLabel: {
    fontSize: 10,
    fontWeight: '600',
    color: '#4b5563',
    textTransform: 'uppercase',
    letterSpacing: 1,
    paddingHorizontal: 12,
    marginBottom: 6,
  },
  sidebarSearchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#030303',
    borderWidth: 1,
    borderColor: '#171717',
    borderRadius: 8,
    marginHorizontal: 12,
    marginBottom: 10,
    paddingHorizontal: 8,
    height: 36,
  },
  sidebarSearchIcon: {
    marginRight: 6,
  },
  sidebarSearchInput: {
    flex: 1,
    color: '#f3f4f6',
    fontSize: 13,
    padding: 0,
    height: '100%',
    ...Platform.select({
      web: {
        outlineStyle: 'none',
      } as any,
      default: {},
    }),
  },
  sidebarSearchClear: {
    padding: 4,
    justifyContent: 'center',
    alignItems: 'center',
  },

  sessionsList: {
    flex: 1,
  },
  sessionItemContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 8,
    gap: 10,
  },
  sessionItemActive: {
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
  },
  sessionTextWrapper: {
    flex: 1,
    justifyContent: 'center',
    paddingVertical: 4,
  },
  sessionText: {
    color: '#8e8e93',
    fontSize: 13.5,
    fontWeight: '400',
    letterSpacing: -0.2,
  },
  sessionTextActive: {
    color: '#ffffff',
    fontWeight: '400',
    letterSpacing: -0.2,
  },
  sessionRenameInput: {
    flex: 1,
    color: '#ffffff',
    fontSize: 13.5,
    padding: 0,
    margin: 0,
    borderBottomWidth: 1,
    borderBottomColor: '#2563eb',
  },
  sessionActionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  sessionActionBtn: {
    padding: 4,
  },
  sidebarFooter: {
    padding: 12,
    borderTopWidth: 1,
    borderTopColor: '#171717',
  },
  userSection: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  userInfo: {
    flex: 1,
  },
  userHonorific: {
    color: '#ffffff',
    fontSize: 13,
    fontWeight: '600',
  },
  userEmail: {
    color: '#4b5563',
    fontSize: 11,
  },
  settingsIconBtn: {
    padding: 6,
  },
  sidebarSettingsPopover: {
    position: 'absolute',
    bottom: 68,
    left: 12,
    right: 12,
    backgroundColor: '#080808',
    borderWidth: 1,
    borderColor: '#171717',
    borderRadius: 12,
    padding: 12,
    zIndex: 110,
    ...Platform.select({
      web: {
        boxShadow: '0 4px 12px rgba(0,0,0,0.4)',
      },
      default: {},
    }),
  },
  sidebarSettingsHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#1e293b',
    marginBottom: 8,
  },
  sidebarSettingsTitle: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  sidebarSettingsItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingVertical: 8,
    paddingHorizontal: 4,
  },
  sidebarSettingsItemText: {
    color: '#ef4444',
    fontSize: 13,
    fontWeight: '600',
  },
  playgroundDrawer: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    width: drawerWidth,
    backgroundColor: '#08111f',
    borderLeftWidth: 1,
    borderLeftColor: '#111827',
    paddingTop: Platform.OS === 'web' ? 40 : 0,
    zIndex: 101,
  },
  playgroundHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    height: 50,
    paddingHorizontal: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#262626',
  },
  playgroundTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  playgroundTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: '#ffffff',
  },
  playgroundTabs: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: '#262626',
  },
  playgroundTab: {
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  playgroundTabActive: {
    borderBottomWidth: 2,
    borderBottomColor: '#2563eb',
  },
  playgroundTabText: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: '600',
  },
  sandboxContainer: {
    flex: 1,
    position: 'relative',
    width: '100%',
    height: '100%',
  },
  webView: {
    flex: 1,
    backgroundColor: '#0d0d0d',
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: '#171717',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    borderWidth: 1,
    borderColor: '#262626',
    padding: 20,
    paddingBottom: 40,
    gap: 8,
  },
  modalTitle: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '700',
    marginBottom: 12,
    textAlign: 'center',
  },
  modelItem: {
    flexDirection: 'row',
    alignItems: 'center',
    height: 48,
    borderRadius: 10,
    paddingHorizontal: 14,
    backgroundColor: '#0d0d0d',
    borderWidth: 1,
    borderColor: '#262626',
    gap: 10,
  },
  modelItemActive: {
    borderColor: '#2563eb',
    backgroundColor: 'rgba(37,99,235,0.05)',
  },
  modelItemText: {
    color: '#9ca3af',
    fontSize: 14,
    flex: 1,
  },
  modelItemTextActive: {
    color: '#ffffff',
    fontWeight: '600',
  },
  inlineModalBackdrop: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    justifyContent: 'flex-end',
    zIndex: 998,
  },
  inlineModalContent: {
    backgroundColor: '#000000',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    borderWidth: 1,
    borderColor: '#171717',
    padding: 18,
    paddingBottom: 30,
    maxHeight: '65%',
  },
  inlineModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingBottom: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#1e293b',
  },
  inlineModalTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  inlineModalTitle: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '700',
    letterSpacing: -0.3,
  },
  inlineModalCloseBtn: {
    width: 32,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 16,
    backgroundColor: '#171717',
  },
  inlineModalSectionLabel: {
    color: '#475569',
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 1,
    textTransform: 'uppercase',
    marginTop: 14,
    marginBottom: 8,
  },
  variantChipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginBottom: 6,
  },
  inlineVariantChip: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#171717',
    backgroundColor: '#0c0c0c',
  },
  inlineVariantChipActive: {
    borderColor: '#3b82f6',
    backgroundColor: 'rgba(59, 130, 246, 0.15)',
  },
  inlineVariantChipText: {
    color: '#64748b',
    fontSize: 12,
    fontWeight: '600',
  },
  inlineVariantChipTextActive: {
    color: '#60a5fa',
  },
  inlineModalList: {
    marginTop: 4,
  },
  inlineModelItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 10,
    backgroundColor: '#0c0c0c',
    borderWidth: 1,
    borderColor: '#171717',
    marginBottom: 6,
    gap: 8,
  },
  inlineModelItemActive: {
    borderColor: '#3b82f6',
    backgroundColor: 'rgba(59, 130, 246, 0.08)',
  },
  inlineModelItemDetails: {
    flex: 1,
  },
  inlineModelName: {
    color: '#94a3b8',
    fontSize: 14,
    fontWeight: '600',
  },
  inlineModelNameActive: {
    color: '#ffffff',
  },
  inlineModelId: {
    color: '#475569',
    fontSize: 10,
    marginTop: 1,
  },
  dropdownBackdrop: {
    position: 'absolute',
    top: -1000,
    bottom: -1000,
    left: -1000,
    right: -1000,
    zIndex: 999,
  },
  variantDropdown: {
    position: 'absolute',
    bottom: 34,
    left: -10,
    backgroundColor: '#080808',
    borderWidth: 1,
    borderColor: '#171717',
    borderRadius: 12,
    padding: 6,
    width: 130,
    zIndex: 1000,
    ...Platform.select({
      web: {
        boxShadow: '0 4px 12px rgba(0,0,0,0.5)',
      },
      default: {},
    }),
  },
  variantDropdownItem: {
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  variantDropdownItemActive: {
    backgroundColor: 'rgba(59, 130, 246, 0.15)',
  },
  variantDropdownText: {
    color: '#94a3b8',
    fontSize: 12,
    fontWeight: '600',
  },
  variantDropdownTextActive: {
    color: '#60a5fa',
  },
  confirmModalBackdrop: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.75)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 2000,
  },
  confirmModalContent: {
    width: '85%',
    maxWidth: 320,
    backgroundColor: '#0c1222',
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#1e293b',
    padding: 24,
    alignItems: 'center',
    ...Platform.select({
      web: {
        boxShadow: '0 10px 25px rgba(0, 0, 0, 0.5)',
      },
      default: {},
    }),
  },
  confirmIcon: {
    marginBottom: 16,
  },
  confirmTitle: {
    color: '#ffffff',
    fontSize: 18,
    fontWeight: '700',
    marginBottom: 8,
  },
  confirmMessage: {
    color: '#94a3b8',
    fontSize: 14,
    textAlign: 'center',
    lineHeight: 20,
    marginBottom: 24,
  },
  confirmButtonsRow: {
    flexDirection: 'row',
    gap: 12,
    width: '100%',
  },
  confirmCancelBtn: {
    flex: 1,
    height: 44,
    borderRadius: 12,
    backgroundColor: '#1e293b',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#334155',
  },
  confirmCancelBtnText: {
    color: '#94a3b8',
    fontSize: 14,
    fontWeight: '600',
  },
  confirmDeleteBtn: {
    flex: 1,
    height: 44,
    borderRadius: 12,
    backgroundColor: '#ef4444',
    justifyContent: 'center',
    alignItems: 'center',
  },
  confirmDeleteBtnText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '600',
  },
  playgroundBackBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  playgroundBackText: {
    color: '#60a5fa',
    fontSize: 14,
    fontWeight: '600',
  },
  playgroundProjectTitle: {
    color: '#94a3b8',
    fontSize: 14,
    fontWeight: '600',
    flex: 1,
    textAlign: 'center',
    marginHorizontal: 12,
  },
  playgroundListContainer: {
    flex: 1,
    backgroundColor: '#050a18',
  },
  playgroundLoadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    gap: 12,
  },
  playgroundLoadingText: {
    color: '#94a3b8',
    fontSize: 13,
  },
  playgroundEmptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 32,
    gap: 12,
  },
  playgroundEmptyIcon: {
    marginBottom: 8,
    opacity: 0.5,
  },
  playgroundEmptyTitle: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '700',
  },
  playgroundEmptyDesc: {
    color: '#475569',
    fontSize: 13,
    textAlign: 'center',
    lineHeight: 18,
  },
  playgroundProjectsList: {
    flex: 1,
  },
  projectItemContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#0c1222',
    borderWidth: 1,
    borderColor: '#1e293b',
    borderRadius: 14,
    padding: 12,
    gap: 12,
  },
  projectItemDetails: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  projectItemIcon: {
    padding: 8,
    backgroundColor: 'rgba(59, 130, 246, 0.1)',
    borderRadius: 10,
  },
  projectItemName: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '600',
  },
  projectItemSub: {
    color: '#475569',
    fontSize: 11,
    marginTop: 2,
  },
  projectRenameInput: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '600',
    borderBottomWidth: 1,
    borderBottomColor: '#2563eb',
    padding: 0,
    margin: 0,
    flex: 1,
  },
  projectActionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  projectActionBtn: {
    padding: 6,
  },
  openPlaygroundBubbleBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: 'rgba(59, 130, 246, 0.15)',
    borderColor: 'rgba(59, 130, 246, 0.3)',
    borderWidth: 1,
    borderRadius: 8,
    paddingVertical: 6,
    paddingHorizontal: 10,
    marginTop: 8,
    alignSelf: 'flex-start',
  },
  openPlaygroundBubbleBtnText: {
    color: '#60a5fa',
    fontSize: 11.5,
    fontWeight: '600',
  },
  refiningHudBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: 'rgba(59, 130, 246, 0.08)',
    borderColor: 'rgba(59, 130, 246, 0.25)',
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 8,
    marginBottom: 8,
  },
  refiningHudLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flex: 1,
  },
  refiningHudText: {
    color: '#60a5fa',
    fontSize: 12.5,
    fontWeight: '600',
  },
  refiningHudCloseBtn: {
    padding: 2,
  },
  playgroundRefineBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingVertical: 6,
    paddingHorizontal: 10,
    backgroundColor: 'rgba(59, 130, 246, 0.1)',
    borderColor: 'rgba(59, 130, 246, 0.25)',
    borderWidth: 1,
    borderRadius: 8,
  },
  playgroundRefineText: {
    color: '#60a5fa',
    fontSize: 13,
    fontWeight: '600',
  },
  playgroundTitleContainer: {
    position: 'absolute',
    left: 80,
    right: 80,
    top: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1,
  },
  modelSearchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#0c0c0c',
    borderWidth: 1,
    borderColor: '#171717',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: Platform.OS === 'ios' ? 10 : 6,
    marginTop: 10,
    marginBottom: 6,
    gap: 8,
  },
  modelSearchInput: {
    color: '#ffffff',
    fontSize: 13,
    flex: 1,
    padding: 0,
    margin: 0,
  },
  modelFavBtn: {
    padding: 6,
  },
  favSectionContainer: {
    borderBottomWidth: 1,
    borderBottomColor: '#171717',
    paddingBottom: 8,
    marginBottom: 6,
  },
  favSectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 8,
    marginBottom: 6,
  },
  favSectionTitle: {
    color: '#eab308',
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  tooltipPopover: {
    position: 'absolute',
    bottom: 32,
    right: 0,
    backgroundColor: '#0c1222',
    borderColor: '#1e293b',
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
    zIndex: 10001,
    minWidth: 100,
    alignItems: 'center',
    justifyContent: 'center',
    ...Platform.select({
      web: {
        boxShadow: '0 4px 12px rgba(0,0,0,0.5)',
      },
      default: {
        shadowColor: '#000000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
        elevation: 4,
      },
    }),
  },
    tooltipPopoverText: {
      color: '#94a3b8',
      fontSize: 10,
      fontWeight: '600',
    },
    mediaPopover: {
      position: 'absolute',
      bottom: Platform.OS === 'ios' ? 120 : 100,
      left: 12,
      backgroundColor: 'rgba(15, 23, 42, 0.95)',
      borderWidth: 1,
      borderColor: '#1e293b',
      borderRadius: 12,
      padding: 6,
      width: 140,
      zIndex: 10002,
      ...Platform.select({
        web: {
          backdropFilter: 'blur(8px)',
          boxShadow: '0 4px 12px rgba(0,0,0,0.5)',
        },
        default: {
          shadowColor: '#000000',
          shadowOffset: { width: 0, height: 4 },
          shadowOpacity: 0.3,
          shadowRadius: 4,
          elevation: 4,
        },
      }),
    },
    mediaPopoverItem: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      paddingVertical: 8,
      paddingHorizontal: 12,
      borderRadius: 8,
    },
    mediaPopoverText: {
      color: '#94a3b8',
      fontSize: 13,
      fontWeight: '600',
    },
    stagedCard: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: '#0c1222',
      borderColor: '#1e293b',
      borderWidth: 1,
      borderRadius: 12,
      padding: 8,
      marginBottom: 8,
      alignSelf: 'flex-start',
      maxWidth: '100%',
      gap: 8,
    },
    stagedThumbnail: {
      width: 36,
      height: 36,
      borderRadius: 6,
      backgroundColor: '#0f172a',
      justifyContent: 'center',
      alignItems: 'center',
    },
    stagedInfo: {
      flexShrink: 1,
      marginRight: 8,
    },
    stagedName: {
      color: '#ffffff',
      fontSize: 12,
      fontWeight: '600',
    },
    stagedSize: {
      color: '#475569',
      fontSize: 10,
      marginTop: 2,
    },
    stagedCloseBtn: {
      padding: 2,
      borderRadius: 10,
      backgroundColor: '#1e293b',
    },
    commandPopupContainer: {
      position: 'absolute',
      bottom: 60,
      left: 12,
      right: 12,
      backgroundColor: 'rgba(15, 23, 42, 0.95)',
      borderRadius: 12,
      borderWidth: 1,
      borderColor: 'rgba(59, 130, 246, 0.2)',
      paddingVertical: 6,
      zIndex: 2000,
      ...Platform.select({
        web: {
          backdropFilter: 'blur(16px)',
          boxShadow: '0 4px 20px rgba(0, 0, 0, 0.4)',
        } as any,
        default: {},
      }),
    },
    commandPopupItem: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 10,
      paddingHorizontal: 16,
    },
    commandPopupActive: {
      backgroundColor: 'rgba(59, 130, 246, 0.15)',
    },
    commandPopupText: {
      color: '#3b82f6',
      fontSize: 13,
      fontWeight: '600',
      marginRight: 8,
    },
    commandPopupDesc: {
      color: '#94a3b8',
      fontSize: 12,
      flex: 1,
    },
    btwBottomSheet: {
      position: 'absolute',
      bottom: 0,
      left: 0,
      right: 0,
      height: Platform.OS === 'web' ? '45%' : 340,
      backgroundColor: 'rgba(10, 15, 30, 0.95)',
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      borderTopWidth: 1.5,
      borderTopColor: 'rgba(59, 130, 246, 0.35)',
      padding: 16,
      zIndex: 999,
      ...Platform.select({
        web: {
          backdropFilter: 'blur(20px)',
          boxShadow: '0 -4px 30px rgba(0, 0, 0, 0.65)',
        } as any,
        default: {},
      }),
    },
    btwBottomSheetHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      borderBottomWidth: 1,
      borderBottomColor: 'rgba(255, 255, 255, 0.08)',
      paddingBottom: 10,
      marginBottom: 10,
    },
    btwBottomSheetTitle: {
      color: '#93c5fd',
      fontSize: 11.5,
      fontWeight: '800',
      letterSpacing: 1.6,
    },
    btwBottomSheetClose: {
      width: 24,
      height: 24,
      borderRadius: 12,
      backgroundColor: 'rgba(255, 255, 255, 0.06)',
      borderColor: 'rgba(255, 255, 255, 0.1)',
      borderWidth: 1,
      justifyContent: 'center',
      alignItems: 'center',
    },
    btwBottomSheetContent: {
      flex: 1,
    },
    btwMessageText: {
      color: '#e2e8f0',
      fontSize: 13.5,
      lineHeight: 20,
      fontWeight: '400',
    },
    drillOptionButton: {
      backgroundColor: '#ffffff',
      borderColor: '#e2e8f0',
      borderWidth: 1,
      borderRadius: 8,
      paddingVertical: 10,
      paddingHorizontal: 16,
      marginVertical: 4,
      alignItems: 'center',
      justifyContent: 'center',
      ...Platform.select({
        web: {
          transition: 'all 0.2s ease',
        } as any,
        default: {},
      }),
    },
    drillOptionSelected: {
      borderColor: '#3b82f6',
      borderWidth: 1.5,
      backgroundColor: '#eff6ff',
      ...Platform.select({
        web: {
          boxShadow: '0 0 8px rgba(59, 130, 246, 0.25)',
        } as any,
        default: {
          shadowColor: '#3b82f6',
          shadowOffset: { width: 0, height: 0 },
          shadowOpacity: 0.25,
          shadowRadius: 4,
          elevation: 1,
        },
      }),
    },
    drillOptionText: {
      color: '#0f172a',
      fontSize: 13.5,
      fontWeight: '600',
    },
    assistantActionsRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginTop: 6,
      marginLeft: 4,
      gap: 12,
    },
    assistantActionBtn: {
      padding: 6,
      borderRadius: 8,
      backgroundColor: 'rgba(255, 255, 255, 0.03)',
      borderWidth: 1,
      borderColor: 'rgba(255, 255, 255, 0.05)',
      justifyContent: 'center',
      alignItems: 'center',
    },
    scrollBottomBtn: {
      position: 'absolute',
      bottom: 20,
      right: 20,
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: 'rgba(59, 130, 246, 0.85)',
      justifyContent: 'center',
      alignItems: 'center',
      elevation: 4,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,
      borderWidth: 1,
      borderColor: 'rgba(255, 255, 255, 0.1)',
    },
    // Workflow Path styles
    workflowContainer: {
      marginTop: 10,
      padding: 12,
      backgroundColor: 'rgba(255, 255, 255, 0.02)',
      borderRadius: 12,
      borderWidth: 1,
      borderColor: 'rgba(255, 255, 255, 0.04)',
    },
    workflowTitle: {
      fontSize: 10,
      fontWeight: '800',
      color: '#3b82f6',
      letterSpacing: 1.2,
      marginBottom: 12,
      textTransform: 'uppercase',
    },
    workflowRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
    },
    workflowSvgCol: {
      width: 30,
      alignItems: 'center',
      position: 'relative',
    },
    workflowCheckOverlay: {
      position: 'absolute',
      top: 13,
      left: 10,
      width: 10,
      height: 10,
      justifyContent: 'center',
      alignItems: 'center',
    },
    workflowTextCol: {
      flex: 1,
      paddingLeft: 6,
      paddingTop: 8,
    },
    workflowLabel: {
      fontSize: 13,
      fontWeight: '500',
      color: '#64748b',
    },
    workflowLabelActive: {
      color: '#ffffff',
      fontWeight: '500',
    },
    workflowLabelFailed: {
      color: '#ef4444',
    },
    workflowStatusText: {
      fontSize: 10,
      color: '#475569',
      marginTop: 2,
    },
    workflowStatusRunning: {
      color: '#3b82f6',
      fontWeight: '600',
    },
    workflowStatusSuccess: {
      color: '#10b981',
      fontWeight: '500',
    },
    workflowStatusFailed: {
      color: '#ef4444',
      fontWeight: '500',
    },
    // Collapsible thinking accordion styles
    thinkingAccordionHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 8,
      paddingHorizontal: 12,
      backgroundColor: 'rgba(255, 255, 255, 0.03)',
      borderColor: 'rgba(255, 255, 255, 0.05)',
      borderWidth: 1,
      borderRadius: 12,
      marginBottom: 8,
      justifyContent: 'space-between',
    },
    thinkingAccordionTitleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    thinkingAccordionText: {
      fontSize: 12,
      color: '#60a5fa',
      fontWeight: '500',
    },
    thinkingAccordionChevron: {
      marginLeft: 6,
    },
    // Detailed thinking bottom sheet logs drawer
    thinkingLogsDrawer: {
      position: 'absolute',
      bottom: 0,
      left: 0,
      right: 0,
      height: Platform.OS === 'web' ? '45%' : 380,
      backgroundColor: '#05070c',
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      borderTopWidth: 1.5,
      borderTopColor: 'rgba(59, 130, 246, 0.25)',
      padding: 16,
      zIndex: 1000,
      ...Platform.select({
        web: {
          backdropFilter: 'blur(20px)',
          boxShadow: '0 -4px 30px rgba(0, 0, 0, 0.7)',
        } as any,
        default: {},
      }),
    },
    thinkingLogsHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      borderBottomWidth: 1,
      borderBottomColor: 'rgba(255, 255, 255, 0.08)',
      paddingBottom: 10,
      marginBottom: 10,
    },
    thinkingLogsTitle: {
      color: '#93c5fd',
      fontSize: 12,
      fontWeight: '800',
      letterSpacing: 1.0,
    },
    thinkingLogsClose: {
      padding: 4,
    },
    thinkingLogLine: {
      flexDirection: 'row',
      marginVertical: 4,
      alignItems: 'flex-start',
    },
    thinkingLogTime: {
      fontSize: 11,
      fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
      color: '#475569',
      width: 70,
    },
    thinkingLogText: {
      flex: 1,
      fontSize: 12,
      fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
      color: '#94a3b8',
      lineHeight: 16,
    },
    // Interactive Action Confirmations Card
    actionConfirmCard: {
      marginTop: 10,
      padding: 14,
      backgroundColor: 'rgba(59, 130, 246, 0.04)',
      borderColor: 'rgba(59, 130, 246, 0.15)',
      borderWidth: 1,
      borderRadius: 14,
      gap: 10,
    },
    actionConfirmTitleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    actionConfirmTitle: {
      fontSize: 11,
      fontWeight: '800',
      color: '#60a5fa',
      letterSpacing: 1.0,
      textTransform: 'uppercase',
    },
    actionConfirmPrompt: {
      fontSize: 14,
      color: '#f1f5f9',
      lineHeight: 20,
    },
    actionConfirmButtons: {
      flexDirection: 'row',
      gap: 8,
      marginTop: 4,
      flexWrap: 'wrap',
    },
    actionConfirmBtnYes: {
      paddingVertical: 8,
      paddingHorizontal: 16,
      backgroundColor: '#10b981',
      borderRadius: 8,
      alignItems: 'center',
      justifyContent: 'center',
    },
    actionConfirmBtnNo: {
      paddingVertical: 8,
      paddingHorizontal: 16,
      backgroundColor: '#ef4444',
      borderRadius: 8,
      alignItems: 'center',
      justifyContent: 'center',
    },
    actionConfirmBtnAlways: {
      paddingVertical: 8,
      paddingHorizontal: 16,
      backgroundColor: '#1e293b',
      borderColor: 'rgba(255, 255, 255, 0.08)',
      borderWidth: 1,
      borderRadius: 8,
      alignItems: 'center',
      justifyContent: 'center',
    },
    actionConfirmBtnText: {
      color: '#ffffff',
      fontSize: 12,
      fontWeight: '600',
    },
  });
